### ISSUE TITLE
setupToken() is called 2 times in compile()

### ISSUE THREAD

**Issue by fadimko** [zordius/lightncandy#155]
https://github.com/zordius/lightncandy/blob/master/src/lightncandy.php#L112
https://github.com/zordius/lightncandy/blob/master/src/lightncandy.php#L122

this code was added in commit bffae91c1eca629ee399c17c6ea016b55cf722a7 for later support of custom delimiters (as it comes from commit message :)), but now second call to `setupToken()` does completely nothing.

**Comment by zordius** [comment]
confirmed as an invalid issue by remove line 122 then execute phpunit.

The first `setupToken()` is required because in `setupToken()` we will set delimiters to default. This includes regex search pattern.

The second time of `setupToken()` is required because in `setupToken()` we will reset delimiters to default. When there is any delimiter changes in the template, after `verifyTemplate()` stage these changes may still there, so we need to reset it before we go `compileTemplate()` stage.

**Comment by fadimko** [comment]
My bad. I should've run tests before creating the issue.
