### ISSUE TITLE
Ability to set a variable within a template

### ISSUE THREAD

**Issue by SirCameronMcAlpine** [zordius/lightncandy#167]
Hi

I would like to write a helper that could set the value of a template variable within the template.
Something like:
{{#set "variableName"}} bla bla value for the variable{{anotherhelper "sdsds"}} {{/set}}

This is possible provided the $options argument of the helper closure is passed by reference.
Unless there is an easier way to do this that I have missed..

Thanks
C

**Comment by zordius** [comment]
All lightncandy features should align with handlebars.js , I need time to look through handlebars.js to ensure how it support this or not.

**Comment by zordius** [comment]
Please refer to https://github.com/wycats/handlebars.js/issues/476 , so far handlebars.js do not support this.

Another way to support this is implement `#set` yourself and store the variable into a global or singleton, then you can get the variable back with your own helper function.

**Comment by zordius** [comment]
Another way to do this is the 'private variable' feature of block helpers, #171 will deal with it.

**Comment by zordius** [comment]
Please read the document README.md and search for `Private variables` , thanks.

**Comment by laurenhamel** [comment]
While this issue has been closed for quite some time, I'd like to make a case for why it should be reopened. As of the latest implementation of handlebars.js, variable assignment can easily be achieved through helpers, both block and inline. For instance, the following works without the need for the explicit declaration of a global and/or private variable:

```js
function set( key, value, context ) {
  context[key] = value;
}
```

When using handlebars.js, I frequently leverage helpers like this to set and then unset a temporary key on the given context. In LightnCandy, however, this is unachievable due to the imposed limitations on helpers. In keeping consistent with handlebars.js, especially when `FLAG_HANDLEBARSJS` is enabled, I do feel that the ability to pass an array by reference to a custom helper should be supported.

**Comment by laurenhamel** [comment]
I'd also like to add that, in JavaScript, objects and arrays are always passed by reference, which is why my example above works, and I think this is the underlying theme of this thread. I feel like LightnCandy has missed the mark in this area.

**Comment by flavi1** [comment]
Not perfect, but less difficult :
When reading php code generated, we can see that closure helper function is "var_exported" in the closure template function.
As long as the variables parameter of the closure template function, this will simply work :
```
        $helpers['set'] = function($k, $v) use(&$in) {
            $in[$k] = $v;
        };
```
tested with
`{{set "var" "myvalue"}}`

**BUT FAILED** with
`{{set "var" "my val ue"}}`

maybe helpers doesn't like spaces?.. Maybe i forget a compilation token?

**Comment by flavi1** [comment]
**However.**
- I don't know if it's hard to reproduce in handlebarsjs. 
- We should want the real variable context, not the global. (if we're between "with" tags for exemple...). We need to be able to target on it (may be another variable to pass by reference?)
- Another "poly-langage" way can be to write a JSON in the template comments to declare globally some vars and parse it before the template engine. Comments should be a good place for "meta" informations...
