### ISSUE TITLE
Memory leak in prepare() method

### ISSUE THREAD

**Issue by skyfortress** [zordius/lightncandy#190]
We are using lightncandy lib with some php daemons and now have noticed some problems with memory leaking. 
```
$phpfunc = include($fn);
 return $phpfunc;
```
I think problem is here, but I don't have any idea how can we deal with it. Any suggestions?

**Comment by zordius** [comment]
Well, prepare() will write php code into tmp file then include() it. Because every tmp file get different name, php opcode cache or APC will grow every time.

Anyway, prepare() is a method for demo or quick test. A better practice is design your own template storage system and save compiled code in your way. You should compile all your templates first, store them for production environment, then start the web. <= this is a better solution.

And, another note is: if you compile() then prepare() every time, you lose lot of performance benefit of lightncandy.

But, if you still like to compile on the fly (maybe development env) , you should config your php opcode cache or APC to stop caching tmp directory.  Refer to https://github.com/zordius/lightncandy/blob/d91c4a4f9cc6487dfd2b78a8ab85560021f7dcb0/src/LightnCandy.php#L110 , the tmp file will be placed under `sys_get_temp_dir()` . Before you start you may check the cache usage from the web page or command line.
