### ISSUE TITLE
To support context updating inside custom helpers

### ISSUE THREAD

**Issue by zordius** [zordius/lightncandy#268]
Check #265 and #266 , will make some changes in lightncandy.

**Comment by zordius** [comment]
try to modify code and found this depends on #269

**Comment by zordius** [comment]
Now custom helpers can update `$options['_this']` just like handlebars.js (updating `this`) and the change will keep persistently. (example: https://github.com/zordius/lightncandy/blob/8283c22e10c3a98c036a135243d076ba0e7b8566/tests/regressionTest.php#L1343-L1359 )

**Comment by laurenhamel** [comment]
I see this issue has been marked as closed for quite some time, but I'm interested in reviving it because I'm still running into an instance where `this` is not getting updated for child contexts. That is, if I make a change to a child context within an `{{#each}}` loop, those changes are not getting carried upward into its parent contexts.

**Comment by theodorejb** [comment]
@laurenhamel Consider checking out [PHP Handlebars](https://github.com/devtheorem/php-handlebars), a modern library with better performance and full support for the Handlebars spec.

Note that you may still have this issue if you modify the context in a helper, and expect the change to propagate to parent blocks as well. This is simply due to PHP's copy-on-write behavior for arrays, whereas in JavaScript objects are used which are passed by reference.
