### ISSUE TITLE
Size in README.md out of date

### ISSUE THREAD

**Issue by reedy** [zordius/lightncandy#340]
https://github.com/zordius/lightncandy/blob/master/README.md says

>SMALL! all PHP files in 188K

My laptop reckons 194KB in src for v1.2.5 in a vendor checkout

**Comment by zordius** [comment]
Thank you for your report! Will fix this later.

**Comment by zordius** [comment]
Well, I just get 193623 bytes in source src, it should be 193623/1024= 189K right?

**Comment by reedy** [comment]
```
reedy@ubuntu64-web-esxi:/var/www/wiki/mediawiki/vendor/zordius/lightncandy/src$ du -h .
216K	.
reedy@ubuntu64-web-esxi:/var/www/wiki/mediawiki/vendor/zordius/lightncandy/src$ du --si .
222k	.
```

**Comment by zordius** [comment]
Well, `du` means 'disk usage' which is harddisk cluster size multiplied with allocated clusters, so you will get different numbers on different file system or cluster size. The number from my side is total exact size of all files (sum of ls -al) .

Anyway, I will update the README because how ever the file size increased 1K these years.

**Comment by zordius** [comment]
Verified again:

```
 ~/lightncandy/src master>cat * |wc -c
  193623
```
